version: '3'
services:
  backend:
    build: backend/.
    command: tail -f /dev/null
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/myapp
    env_file:
      - postgresql.env
  node:
    build: node/.
    command: node hitbtc.js
    #command: tail -f /dev/null
    env_file:
      - ./node.env
    volumes:
      - ./node:/myapp
      - ./shared:/shared
    links:
      - postgres
  postgres:
    image: postgres:10-alpine
    env_file:
      - postgresql.env
  pgadmin4:
    image: chorss/docker-pgadmin4
    restart: always
    ports:
      - '5454:5050'
    links:
      - postgres
    volumes:
      - ./shared:/shared
